export const API = 'API';
export const SET_USER_INFO = 'SET_USER_INFO';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const ACCOUNT_CREATED = 'ACCOUNT_CREATED';
export const RESET_USER_INFO = 'RESET_USER_INFO';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER = 'UPDATE_USER';
export const SET_ALL_TRAINERS = 'SET_ALL_TRAINERS';
export const SET_ALL_TRAINEES = 'SET_ALL_TRAINEES';

export const SET_ALL_ORGS = 'SET_ALL_ORGS';
export const ADD_ORG = 'ADD_ORG';
export const REMOVE_ORG = 'REMOVE_ORG';
export const UPDATE_ORG = 'UPDATE_ORG';
export const SET_SINGLE_ORG = 'SET_SINGLE_ORG';

export const SET_ALL_CATEGORIES = 'SET_ALL_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const REMOVE_COURSE = 'REMOVE_COURSE';

export const SET_ALL_CHAPTERS = 'SET_ALL_CHAPTERS';
export const SET_SINGLE_CHAPTER = 'SET_SINGLE_CHAPTER';
export const UPDATE_CHAPTER = 'UPDATE_CHAPTER';
export const REMOVE_CHAPTER = 'REMOVE_CHAPTER';

export const SET_ALL_COURSES = 'SET_ALL_COURSES';
export const SET_SINGLE_COURSE = 'SET_SINGLE_COURSES';

export const SET_ALL_USERS = 'SET_ALL_USERS';
export const SET_SINGLE_USER = 'GET_SINGLE_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_COURSE = 'ADD_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';

export const SET_ALL_REQUESTS = 'SET_ALL_REQUESTS';
export const REMOVE_REQUEST = 'REMOVE_REQUEST';
export const UPDATE_REQUEST = 'UPDATE_REQUEST';

